{{- if eq .Values.ingress.default.type "traefik" }}
{{- $gateway := .Values.gateway }}
{{- $serviceName := include "drupal.servicename" . }}
{{- $mainDomain := include "drupal.domain" . | trim }}

# HTTPRoute for the main domain (and domainPrefixes).
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
  {{- if (index .Values "silta-release").downscaler.enabled }}
  annotations:
    auto-downscale/down: "false"
    auto-downscale/last-update: {{ dateInZone "2006-01-02T15:04:05.999Z" (now) "UTC" }}
    auto-downscale/label-selector: "release={{ .Release.Name }}"
    auto-downscale/services: {{ $serviceName }}
    {{- if and (index .Values "silta-release").downscaler.releaseMinAge (ne (index .Values "silta-release").downscaler.releaseMinAge "") }}
    auto-downscale/min-age: {{ (index .Values "silta-release").downscaler.releaseMinAge }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ $gateway.name }}
      namespace: {{ $gateway.namespace }}
  hostnames:
    - {{ $mainDomain | quote }}
    {{- range $index, $prefix := .Values.domainPrefixes }}
    {{- $params := dict "prefix" $prefix }}
    - '{{ template "drupal.domain" (merge $params $ ) }}'
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $serviceName }}
          port: 80

{{- range $ingress_index, $ingress := $.Values.ingress }}

{{- $ingress_in_use := false }}
{{- range $domain_index, $domain := $.Values.exposeDomains }}
  {{- $domain := mergeOverwrite (deepCopy $.Values.exposeDomainsDefaults) $domain }}
  {{- if $domain.ingress }}
    {{- if eq $ingress_index $domain.ingress }}
      {{- $ingress_in_use = true }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if $ingress_in_use }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-drupal-{{ $ingress_index }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ $gateway.name }}
      namespace: {{ $gateway.namespace }}
  hostnames:
    {{- range $domain_index, $domain := $.Values.exposeDomains }}
    {{- $domain := mergeOverwrite (deepCopy $.Values.exposeDomainsDefaults) $domain }}
    {{- if eq $domain.ingress $ingress_index }}
    - {{ $domain.hostname | quote }}
    {{- end }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "drupal.servicename" $ }}
          port: 80
{{- end }}
{{- end }}

{{- end }}
