name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add wunder-charts https://storage.googleapis.com/charts.wdr.io
          helm repo add percona https://percona.github.io/percona-helm-charts/
          helm repo add jouve https://jouve.github.io/charts/
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io/
          helm repo add instana https://agents.instana.io/helm
          helm repo add nfs-subdir https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
          helm repo add twuni https://twuni.github.io/docker-registry.helm
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
